//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperWriting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string WidthLimit {
            get {
                return ((string)(this["WidthLimit"]));
            }
            set {
                this["WidthLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HyperRef {
            get {
                return ((bool)(this["HyperRef"]));
            }
            set {
                this["HyperRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#\\#([{SEQ 一级标题 \\c}-{SEQ 公式}])")]
        public string Formula {
            get {
                return ((string)(this["Formula"]));
            }
            set {
                this["Formula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Figure [{SEQ 图片}]  #")]
        public string Figure {
            get {
                return ((string)(this["Figure"]));
            }
            set {
                this["Figure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Table [{SEQ 表格}]  #")]
        public string Table {
            get {
                return ((string)(this["Table"]));
            }
            set {
                this["Table"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{SEQ 一级标题}  #")]
        public string Header1 {
            get {
                return ((string)(this["Header1"]));
            }
            set {
                this["Header1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{SEQ 一级标题 \\c}.{SEQ 二级标题}  #")]
        public string Header2 {
            get {
                return ((string)(this["Header2"]));
            }
            set {
                this["Header2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{SEQ 一级标题 \\c}.{SEQ 二级标题 \\c}.{SEQ 三级标题}  #")]
        public string Header3 {
            get {
                return ((string)(this["Header3"]));
            }
            set {
                this["Header3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Above")]
        public global::PaperWriting.TargetPosition FigurePosition {
            get {
                return ((global::PaperWriting.TargetPosition)(this["FigurePosition"]));
            }
            set {
                this["FigurePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Above")]
        public global::PaperWriting.TargetPosition TablePosition {
            get {
                return ((global::PaperWriting.TargetPosition)(this["TablePosition"]));
            }
            set {
                this["TablePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("公式")]
        public string FormulaStyle {
            get {
                return ((string)(this["FormulaStyle"]));
            }
            set {
                this["FormulaStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("图片")]
        public string FigureStyle {
            get {
                return ((string)(this["FigureStyle"]));
            }
            set {
                this["FigureStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("表格")]
        public string TableStyle {
            get {
                return ((string)(this["TableStyle"]));
            }
            set {
                this["TableStyle"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaperWriting_")]
        public string BookmarkPrefix {
            get {
                return ((string)(this["BookmarkPrefix"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("标题 1")]
        public string Header1Style {
            get {
                return ((string)(this["Header1Style"]));
            }
            set {
                this["Header1Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("标题 2")]
        public string Header2Style {
            get {
                return ((string)(this["Header2Style"]));
            }
            set {
                this["Header2Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("标题 3")]
        public string Header3Style {
            get {
                return ((string)(this["Header3Style"]));
            }
            set {
                this["Header3Style"] = value;
            }
        }
    }
}
